Run python grok_radiator.py || true
[START] Inicjalizacja Grok Radiation Engine...
[ERROR] Błąd podczas komunikacji z API Groka: HTTP Error 400: {"code":"invalid-argument","error":"Model not found: grok-4.1-fast"}
